server:
  port: 8088


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/purchase?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: toor
  data:
    redis:
      host: localhost
      port: 6379
      database: 5

mybatis:
    mapper-locations: classpath:mapper/*.xml